### ISSUE TITLE
celsius toggle

### ISSUE THREAD

**Issue by kavigupta** [kavigupta/urbanstats#136]
reported by twitter user averyhatestwt

**Comment by lukebrody** [comment]
Should we default "use imperial units" to on based on the user's browser locale settings?

**Comment by kavigupta** [comment]
The main reason not to tie this to Use Imperial Units is that currently statistics are defined in terms of km (pw density (r=1km)) and °F (days with mean temp > 90°F). So the most consistent set of units is metric except for temperature

**Comment by lukebrody** [comment]
What about just changing that to > 32ºC
But separate toggle is also fine
