### ISSUE TITLE
Comparison page for international and domestic only pages has an issue 

### ISSUE THREAD

**Issue by kavigupta** [kavigupta/urbanstats#276]
Not sure what's going on with area/compactness, and it should at least provide census population.

https://urbanstats.org/comparison.html?longnames=%5B%22Daegu-gwangyeoksi%2C+Korea%2C+Republic+of%22%2C%22Los+Angeles+city%2C+California%2C+USA%22%5D

**Comment by lukebrody** [comment]
There doesn't seem to be anything wrong with this now

**Comment by kavigupta** [comment]
Yeah it looks good
