### ISSUE TITLE
Make links discord proof

### ISSUE THREAD

**Issue by kavigupta** [kavigupta/urbanstats#299]
Discord ruins the links:

https://urbanstats.org/statistic.html?statname=Households+With+no+Vehicle+%25&article_type=Subnational+Region&start=21&amount=20&order=ascending&universe=USA

https://urbanstats.org/statistic.html?statname=Households+With+no+Vehicle+%25%26article_type%3DSubnational+Region&start=21&amount=20&order=ascending&universe=USA

Not sure how to fix this, but probably some kind of processing could work?

**Comment by lukebrody** [comment]
This isn't for links in general, but for this specific link, where the stat name ends with '%', which is encoded as %25&, which discord for whatever reason translates to %25%26

**Comment by lukebrody** [comment]
Submitted discord bug 48554570

**Comment by lukebrody** [comment]
(Messenger doesn't do this)

**Comment by lukebrody** [comment]
Apple messages doesn't do this

**Comment by kavigupta** [comment]
hmm we could just special case this? just translate `%25%26` to `%25&`

**Comment by lukebrody** [comment]
Oh yeah that would work… maybe Discord will fix it tho… let’s wait a little while. One less special case for us
