### ISSUE TITLE
Years are interacting incorrectly with universe specific statistics

### ISSUE THREAD

**Issue by kavigupta** [kavigupta/urbanstats#499]
Eg on the corpus christi page, when universe is set to "world" some statistics are showing but only the 2010 equivalents

https://urbanstats.org/article.html?longname=Corpus+Christi+city%2C+Texas%2C+USA&universe=world

Desired behavior: no statistics should show up

**Comment by lukebrody** [comment]
This is broken as of 63ca79cd so it's probably not stat checkbox tree...

**Comment by lukebrody** [comment]
Broken on 88686942
