### ISSUE TITLE
Arrows broken on narrow screens

### ISSUE THREAD

**Issue by kavigupta** [kavigupta/urbanstats#631]
Only one arrow shows up
![1000052028](https://github.com/user-attachments/assets/75d9373d-0a8e-46fe-95ba-e76e118d4e81)

**Comment by lukebrody** [comment]
They’re wrapping

**Comment by lukebrody** [comment]
RCA of this is that our mobile screenshots are too narrow to be useful

**Comment by kavigupta** [comment]
No this is true on my mobile screen. I think it might be because of the weird scaling that was introduced a while ago

**Comment by kavigupta** [comment]
I think somehow it's scaling to like the number of pixels or something instead of the size of the screen physically

**Comment by lukebrody** [comment]
Confirmed 0b42c95e is the breaking commit
