### ISSUE TITLE
Do not show negative numbers in quiz timer

### ISSUE THREAD

**Issue by kavigupta** [kavigupta/urbanstats#664]
We should fix this by eg replacing the timer with a button that says reload when it hits 0.

![Screenshot_20241128-000002](https://github.com/user-attachments/assets/b0286d67-56f1-4ed9-96f1-a6a28e223b7e)

**Comment by lukebrody** [comment]
We can just make next quiz a link that navigates to the next quiz if we're in "today" mode, or goes to the next quiz if we're in "date" mode.
