### ISSUE TITLE
Juxtastat friend link

### ISSUE THREAD

**Issue by lukebrody** [kavigupta/urbanstats#757]
> Friend link feature plz 🙏 send like `juxtastat.org/id?id=alblabkabk2333&name=guava` and it has a button to add me as guava

> We should probably refactor quiz data to be a logic class so we don’t have to do weird reloads
And then we can use navigator effects

How will UI for this work, if at all?

**Comment by kavigupta** [comment]
I think probably the cleanest way to do this would be to just make it its own page?
